name: CI Pipeline

on:
  push:
    branches:
      - task-1
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pandas google-play-scraper==1.2.3

    - name: Run scraper
      run: |
        python scripts/scrape_reviews.py

    - name: Run preprocessor
      run: |
        python scripts/preprocess_reviews.py

    - name: Verify output
      run: |
        if [ ! -f "cleaned_reviews.csv" ]; then
          echo "Error: cleaned_reviews.csv not found"
          exit 1
        fi
        echo "Pipeline completed successfully"